Repository AlexsLemonade/refinebio, pull requests merged in 2018-06, with the labels that each got.

#298 Use Detailed View and Add `order_by` to Sample List
  api/data_refinery_api/tests.py
  api/data_refinery_api/views.py
  foreman/data_refinery_foreman/surveyor/geo.py
Labels: in progress, review

#301 count filters based on results of query
  api/data_refinery_api/views.py
Labels: in progress, review

#299 Explicitly Label Result Pipeline
  api/data_refinery_api/serializers.py
  api/data_refinery_api/tests.py
  common/data_refinery_common/models/models.py
  foreman/data_refinery_foreman/surveyor/geo.py
  workers/data_refinery_workers/processors/agilent_twocolor.py
  workers/data_refinery_workers/processors/array_express.py
  workers/data_refinery_workers/processors/illumina.py
  workers/data_refinery_workers/processors/no_op.py
  workers/data_refinery_workers/processors/salmon.py
Labels: in progress, review

#302 Makes association tables unique, adds organisms to geo experiments.
  common/data_refinery_common/models/models.py
  foreman/data_refinery_foreman/surveyor/array_express.py
  foreman/data_refinery_foreman/surveyor/geo.py
  foreman/data_refinery_foreman/surveyor/sra.py
Labels: in progress, review

#304 Sorts sample dictionaries before trying to extract the title in harmony.
  foreman/data_refinery_foreman/surveyor/harmony.py
  foreman/data_refinery_foreman/surveyor/test_harmony.py
Labels: in progress, review

#293 Kurtwheeler/normalize platforms
  .circleci/config.yml
  api/data_refinery_api/serializers.py
  api/data_refinery_api/tests.py
  api/data_refinery_api/views.py
  common/Dockerfile
  common/Dockerfile.migrations
  common/Dockerfile.tests
  common/data_refinery_common/message_queue.py
  common/data_refinery_common/microarray.py
  common/data_refinery_common/models/models.py
  common/data_refinery_common/settings.py
  common/data_refinery_common/test_microarray.py
  common/data_refinery_common/test_utils.py
  common/data_refinery_common/utils.py
  common/make_migrations.sh
  common/run_tests.sh
  common/setup.py
  common/supported_platforms.csv
  common/test-files/97_(Mouse430_2).CEL.gz
  common/test-files/C30057.CEL.gz
  common/test-files/SG2_u34a.CEL.gz
  config/readable_platform_names.csv
  config/supported_microarray_platforms.csv
  config/supported_rnaseq_platforms.txt
  foreman/data_refinery_foreman/settings.py
  foreman/data_refinery_foreman/surveyor/array_express.py
  foreman/data_refinery_foreman/surveyor/external_source.py
  foreman/data_refinery_foreman/surveyor/geo.py
  foreman/data_refinery_foreman/surveyor/sra.py
  foreman/data_refinery_foreman/surveyor/test_geo.py
  foreman/dockerfiles/Dockerfile.foreman
  workers/data_refinery_workers/downloaders/array_express.py
  workers/dockerfiles/Dockerfile.downloaders
  workers/install_affy_only.R
Labels: in progress, review

#306 Fix a bad merge I noticed while dealing with new merge conflicts.
  foreman/data_refinery_foreman/surveyor/sra.py
Labels: in progress, review

#309 Slice tximport Output Into Smashable Individual Files
  workers/data_refinery_workers/processors/requirements.in
  workers/data_refinery_workers/processors/requirements.txt
  workers/data_refinery_workers/processors/salmon.py
  workers/data_refinery_workers/processors/test_salmon.py
  workers/data_refinery_workers/processors/tximport.R
  workers/install_tximport.R
Labels: in progress, review, salmon, smasher

#310 Use assembly version from Ensembl's API rather than hardcoding it. St…
  common/data_refinery_common/models/models.py
  foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py
  foreman/data_refinery_foreman/surveyor/test_transcriptome_species.json
  foreman/data_refinery_foreman/surveyor/transcriptome_index.py
  workers/data_refinery_workers/downloaders/transcriptome_index.py
  workers/data_refinery_workers/processors/test_transcriptome_index.py
  workers/data_refinery_workers/processors/transcriptome_index.py
Labels: in progress, review

#308 Kurtwheeler routing refactor
  api/data_refinery_api/serializers.py
  common/data_refinery_common/job_lookup.py
  common/data_refinery_common/message_queue.py
  common/data_refinery_common/models/models.py
  common/data_refinery_common/settings.py
  common/data_refinery_common/test_utils.py
  common/data_refinery_common/utils.py
  common/make_migrations.sh
  config/readable_affymetrix_names.csv
  foreman/data_refinery_foreman/settings.py
  foreman/data_refinery_foreman/surveyor/array_express.py
  foreman/data_refinery_foreman/surveyor/external_source.py
  foreman/data_refinery_foreman/surveyor/geo.py
  foreman/data_refinery_foreman/surveyor/management/commands/survey_all.py
  foreman/data_refinery_foreman/surveyor/sra.py
  foreman/data_refinery_foreman/surveyor/test_array_express.py
  foreman/data_refinery_foreman/surveyor/test_external_source.py
  foreman/data_refinery_foreman/surveyor/test_geo.py
  foreman/data_refinery_foreman/surveyor/test_sra.py
  foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py
  foreman/data_refinery_foreman/surveyor/transcriptome_index.py
  update_my_docker_images.sh
  workers/data_refinery_workers/downloaders/array_express.py
  workers/data_refinery_workers/downloaders/geo.py
  workers/data_refinery_workers/downloaders/sra.py
  workers/data_refinery_workers/downloaders/utils.py
Labels: in progress, review

#312 Add `platforms` property to Experiment
  api/data_refinery_api/serializers.py
  api/data_refinery_api/tests.py
  common/data_refinery_common/models/models.py
Labels: in progress, review

#314 Kurtwheeler fix foreman
  api/data_refinery_api/views.py
  common/data_refinery_common/message_queue.py
  common/data_refinery_common/models/jobs.py
  foreman/data_refinery_foreman/foreman/main.py
  foreman/data_refinery_foreman/foreman/test_main.py
  foreman/data_refinery_foreman/surveyor/external_source.py
  foreman/data_refinery_foreman/surveyor/test_transcriptome_index.py
  workers/data_refinery_workers/downloaders/transcriptome_index.py
  workers/data_refinery_workers/downloaders/utils.py
Labels: in progress, review

#316 Add CORS support on API
  api/data_refinery_api/settings.py
  api/requirements.in
  api/requirements.txt
Labels: in progress, review

#318 Use `is_public` and `is_processed` fields // API returns accessions rather than IDs
  api/data_refinery_api/serializers.py
  api/data_refinery_api/views.py
  common/data_refinery_common/models/models.py
  workers/data_refinery_workers/processors/test_utils.py
  workers/data_refinery_workers/processors/utils.py
Labels: in progress, review

#315 Add more envs, improve deployment, stand up staging stack
  .circleci/config.yml
  .circleci/run_terraform.sh
  .circleci/s3_tfstate/main.tf
  .circleci/s3_tfstate/terraform.tfstate
  .circleci/s3_tfstate/terraform.tfstate.backup
  .circleci/s3_tfstate/variables.tf
  .circleci/update_docker_img.sh
  .gitattributes
  api/environments/local
  api/environments/prod
  api/run_tests.sh
  api/serve.sh
  api/serve_production.sh
  common/environments/local
  common/environments/prod
  common/make_migrations.sh
  foreman/environments/local
  foreman/environments/prod
  foreman/nomad-job-specs/surveyor.nomad.tpl
  foreman/run_surveyor.sh
  foreman/run_tests.sh
  format_nomad_with_env.sh
  infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
  infrastructure/deploy.sh
  infrastructure/disk.tf
  infrastructure/environments/dev.tfvars
  infrastructure/environments/prod.tfvars
  infrastructure/environments/staging.tfvars
  infrastructure/instances.tf
  infrastructure/task-definitions/worker.json.secret
  infrastructure/terraform.tfvars
  infrastructure/users.tf
  infrastructure/variables.tf
  prepare_image.sh
  run_nomad.sh
  run_shell.sh
  update_my_docker_images.sh
  workers/environments/local
  workers/environments/prod
  workers/environments/test
  workers/nomad-job-specs/affymetrix.nomad.tpl
  workers/nomad-job-specs/downloader.nomad.tpl
  workers/nomad-job-specs/illumina.nomad.tpl
  workers/nomad-job-specs/no_op.nomad.tpl
  workers/nomad-job-specs/salmon.nomad.tpl
  workers/nomad-job-specs/smasher.nomad.tpl
  workers/nomad-job-specs/transcriptome.nomad.tpl
  workers/run_tests.sh
  workers/tester.sh
Labels: in progress, review

#331 add accession code filtering and tests
  api/data_refinery_api/tests.py
  api/data_refinery_api/views.py
Labels: in progress, review

#334 Aspera Downloader for GEO
  workers/data_refinery_workers/downloaders/geo.py
  workers/data_refinery_workers/downloaders/test_geo.py
Labels: in progress, review

#327 Hopefully better Linux IP address detection
  README.md
  common.sh
Labels: in progress, review

#338 Remove unnecessary R packages from affymetrix docker image
  workers/affymetrix_dependencies.R
Labels: in progress, review

#344 Adds API Token
  api/data_refinery_api/serializers.py
  api/data_refinery_api/settings.py
  api/data_refinery_api/tests.py
  api/data_refinery_api/urls.py
  api/data_refinery_api/views.py
  common/data_refinery_common/models/__init__.py
  common/data_refinery_common/models/models.py
Labels: in progress, review

#349 Prevent the downloaders tests from timing out in CCI.
  .circleci/config.yml
Labels: review

#345 Improve scripts and documentation
  README.md
  api/run_tests.sh
  common/run_tests.sh
  foreman/run_tests.sh
  format_nomad_with_env.sh
  infrastructure/deploy.sh
  prepare_image.sh
  run_all_tests.sh
  run_nomad.sh
  run_postgres.sh
  update_models.sh
  workers/run_tests.sh
Labels: in progress, review

#353 Add 1 git-crypt collaborator
  .git-crypt/keys/default/0/110BA773813D87DFB097184A685EBAA08E007E1D.gpg
Labels: in progress, review

#339 Optimize Salmon Index Calculations
  workers/data_refinery_workers/processors/salmon.py
  workers/data_refinery_workers/processors/test_salmon.py
Labels: in progress, review

#347 Add TSV Metadata to Smasher Output
  workers/data_refinery_workers/processors/smasher.py
  workers/data_refinery_workers/processors/test_smasher.py
Labels: in progress, review

#356 Fixes ps sometimes not outputting enough output to show up in grep.
  foreman/run_tests.sh
  run_all_tests.sh
Labels: in progress, review

#357 Switch from Ubuntu to High Availablity Keyserver
  common/Dockerfile.tests
  workers/dockerfiles/Dockerfile.affymetrix
  workers/dockerfiles/Dockerfile.downloaders
  workers/dockerfiles/Dockerfile.illumina
  workers/dockerfiles/Dockerfile.salmon
Labels: in progress, review

#340 Add Support for Broader Set of Illumina Beadchip Platforms
  .circleci/config.yml
  common/data_refinery_common/models/__init__.py
  common/data_refinery_common/models/models.py
  workers/data_refinery_workers/processors/agilent_twocolor.py
  workers/data_refinery_workers/processors/array_express.py
  workers/data_refinery_workers/processors/detect_database.R
  workers/data_refinery_workers/processors/illumina.R
  workers/data_refinery_workers/processors/illumina.py
  workers/data_refinery_workers/processors/no_op.py
  workers/data_refinery_workers/processors/salmon.py
  workers/data_refinery_workers/processors/smasher.py
  workers/data_refinery_workers/processors/test_geo.py
  workers/data_refinery_workers/processors/test_smasher.py
  workers/data_refinery_workers/processors/utils.py
  workers/dockerfiles/Dockerfile.illumina
  workers/illumina_dependencies.R
  workers/run_tests.sh
Labels: in progress, review

#352 Reduces size of test_volume on developer machines
  workers/data_refinery_workers/processors/test_transcriptome_index.py
  workers/data_refinery_workers/processors/transcriptome_index.py
  workers/run_tests.sh
Labels: in progress, review

#358 Fixes some bad resource references in terraform networking config
  infrastructure/networking.tf
Labels: in progress, review

#351 Prevent duplicate Array Express processor jobs
  DEBUGGING.md
  foreman/data_refinery_foreman/surveyor/external_source.py
  foreman/data_refinery_foreman/surveyor/test_geo.py
  workers/data_refinery_workers/downloaders/array_express.py
  workers/data_refinery_workers/downloaders/geo.py
  workers/data_refinery_workers/downloaders/sra.py
  workers/data_refinery_workers/downloaders/test_array_express.py
  workers/data_refinery_workers/downloaders/test_geo.py
  workers/data_refinery_workers/downloaders/utils.py
Labels: in progress, review

#355 Dualsmash Part 1: Bug Fixes and Test Files
  api/data_refinery_api/admin.py
  api/data_refinery_api/urls.py
  common/data_refinery_common/models/models.py
  foreman/data_refinery_foreman/surveyor/external_source.py
  foreman/data_refinery_foreman/surveyor/geo.py
  foreman/data_refinery_foreman/surveyor/sra.py
  foreman/data_refinery_foreman/surveyor/transcriptome_index.py
  workers/data_refinery_workers/processors/management/commands/run_processor_job.py
  workers/data_refinery_workers/processors/salmon.py
  workers/data_refinery_workers/processors/smasher.py
  workers/data_refinery_workers/processors/test_smasher.py
  workers/data_refinery_workers/processors/transcriptome_index.py
  workers/dockerfiles/Dockerfile.affymetrix_local
  workers/run_tests.sh
Labels: in progress, review
