Repository AlexsLemonade/refinebio, pull requests merged in 2018-08, with the labels that each got.

#465 Uses prepare_image.sh to build common images so we get that nice retr…
  common/dockerfiles/Dockerfile.common_tests
  common/dockerfiles/Dockerfile.migrations
  common/make_migrations.sh
  common/run_tests.sh
Labels: review

#464 Add Migration File for Recent Model Changes
  common/data_refinery_common/migrations/0007_auto_20180731_1946.py
Labels: in progress, review

#454 Added pretty_platforms to Experiment
  api/data_refinery_api/serializers.py
  common/data_refinery_common/models/models.py
Labels: in progress, review

#463 Remove has_publication filter if 0
  api/data_refinery_api/tests.py
  api/data_refinery_api/views.py
Labels: in progress, review

#462 Adds the configuration changes necessary to use terraform's remote S3…
  .circleci/run_terraform.sh
  foreman/data_refinery_foreman/settings.py
  infrastructure/backend.tf
  infrastructure/deploy.sh
  infrastructure/networking.tf
  workers/data_refinery_workers/processors/smasher.py
Labels: review

#467 Add `publication_authors` Property and Scrape Authors List from PubMed
  api/data_refinery_api/serializers.py
  api/data_refinery_api/views.py
  common/data_refinery_common/migrations/0008_experiment_publication_authors.py
  common/data_refinery_common/models/models.py
  foreman/data_refinery_foreman/surveyor/array_express.py
  foreman/data_refinery_foreman/surveyor/geo.py
  foreman/data_refinery_foreman/surveyor/sra.py
  foreman/data_refinery_foreman/surveyor/test_geo.py
  foreman/data_refinery_foreman/surveyor/utils.py
Labels: in progress, review

#468 Fixes up some infra issues in dev stacks, restarts API with latest im…
  infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
  infrastructure/deploy.sh
  infrastructure/disk.tf
  infrastructure/networking.tf
  infrastructure/variables.tf
Labels: review

#472 Adds a file that was forgotten in a previous PR.
  infrastructure/init_terraform.sh
Labels: in progress, review

#471 Expose scale_by to the API
  api/data_refinery_api/serializers.py
Labels: in progress, review

#474 Fixes foreman requeuing jobs it shouldn't. Also a couple other minor bugs
  foreman/data_refinery_foreman/foreman/main.py
  foreman/data_refinery_foreman/foreman/test_main.py
  foreman/data_refinery_foreman/surveyor/management/commands/survey_sra.py
  workers/data_refinery_workers/processors/salmon.py
Labels: in progress, review

#473 Fixes Two Issues Which Caused Extra Jobs of the Wrong Type
  common/data_refinery_common/job_lookup.py
  common/data_refinery_common/message_queue.py
  foreman/data_refinery_foreman/surveyor/geo.py
  workers/data_refinery_workers/downloaders/geo.py
  workers/data_refinery_workers/downloaders/utils.py
Labels: in progress, review

#475 Don't let running the migrations try to talk to AWS.
  infrastructure/deploy.sh
Labels: in progress, review

#476 Moves from HStoreField to JSONField
  api/data_refinery_api/serializers.py
  common/data_refinery_common/migrations/0009_auto_20180802_1758.py
  common/data_refinery_common/models/models.py
Labels: in progress, review

#479 Makes Nomad Hush Up
  infrastructure/nomad-configuration/client.tpl.hcl
  infrastructure/nomad-configuration/lead_server.hcl
  infrastructure/nomad-configuration/server.tpl.hcl
Labels: in progress, review

#483 Update No-Op Dockerfile to Use Latest Identifier Refinery Archive'
  workers/dockerfiles/Dockerfile.no_op
Labels: review

#485 De-duplicate Rows from NO_OP Processor
  workers/data_refinery_workers/processors/gene_convert.R
  workers/data_refinery_workers/processors/test_no_op.py
Labels: in progress, review

#482 Fixes uploading to s3, improves resiliency of Foreman, and fixes a bl…
  api/data_refinery_api/settings.py
  common/data_refinery_common/models/models.py
  common/data_refinery_common/settings.py
  foreman/data_refinery_foreman/foreman/main.py
  workers/data_refinery_workers/downloaders/geo.py
  workers/data_refinery_workers/processors/no_op.py
  workers/data_refinery_workers/processors/utils.py
  workers/data_refinery_workers/settings.py
Labels: review

#489 Add an acm_certificate_validation resource to prevent deploys from be…
  infrastructure/networking.tf
Labels: in progress, review

#484 Add sample_metadata to experiments endpoint
  api/data_refinery_api/serializers.py
  common/data_refinery_common/models/models.py
  common/data_refinery_common/models/test_models.py
Labels: review

#487 Improvements for Different Illumina Headers in NO_OP
  workers/data_refinery_workers/processors/gene_convert_illumina.R
  workers/data_refinery_workers/processors/no_op.py
  workers/data_refinery_workers/processors/test_no_op.py
  workers/run_tests.sh
Labels: in progress, review

#492 Add force-copy argument to terraform init so it will switch backends.
  infrastructure/init_terraform.sh
Labels: in progress, review

#494 Change database instance type, change ASG thresholds, and remove pers…
  infrastructure/environments/dev.tfvars
  infrastructure/environments/prod.tfvars
  infrastructure/environments/staging.tfvars
  infrastructure/instances.tf
  infrastructure/logging.tf
  infrastructure/variables.tf
Labels: in progress, review

#495 Kurtwheeler fix rebuilding docker imgs
  .circleci/run_terraform.sh
  .circleci/slackpost.sh
  .circleci/update_docker_img.sh
Labels: in progress, review

#496 Tiny Fix in Slackbot Script
  .circleci/slackpost.sh
  foreman/data_refinery_foreman/foreman/main.py
Labels: in progress, review

#497 Fix restarting API server after deploys. Switch AGS to 1b.
  infrastructure/deploy.sh
  infrastructure/instances.tf
Labels: in progress, review

#498 Dont S3-Sync OriginalFiles // Adds delete_local_files command
  workers/data_refinery_workers/processors/illumina.py
  workers/data_refinery_workers/processors/management/commands/delete_local_files.py
  workers/data_refinery_workers/processors/test_geo.py
  workers/data_refinery_workers/processors/utils.py
Labels: in progress, review

#502 Make the Foreman log why it's restarting lost jobs and perhaps make i…
  foreman/data_refinery_foreman/foreman/main.py
Labels: in progress, review

#501 Adds converted GPLs and A-GEODs to supported microarray list.
  common/data_refinery_common/test_utils.py
  common/data_refinery_common/utils.py
  foreman/data_refinery_foreman/surveyor/array_express.py
Labels: in progress, review

#511 Ensure get_ip_address returns a single IP
  common.sh
Labels: in progress, review

#481 Update Processor Info Dynamically
  api/data_refinery_api/serializers.py
  api/data_refinery_api/tests.py
  common/data_refinery_common/migrations/0010_auto_20180806_2107.py
  common/data_refinery_common/models/models.py
  workers/data_refinery_workers/processors/affymetrix.yml
  workers/data_refinery_workers/processors/agilent_twocolor.py
  workers/data_refinery_workers/processors/agilent_twocolor.yml
  workers/data_refinery_workers/processors/array_express.py
  workers/data_refinery_workers/processors/illumina.py
  workers/data_refinery_workers/processors/illumina.yml
  workers/data_refinery_workers/processors/multiqc.yml
  workers/data_refinery_workers/processors/no_op.py
  workers/data_refinery_workers/processors/no_op.yml
  workers/data_refinery_workers/processors/salmon.py
  workers/data_refinery_workers/processors/salmon_quant.yml
  workers/data_refinery_workers/processors/salmontools.yml
  workers/data_refinery_workers/processors/smasher.py
  workers/data_refinery_workers/processors/smasher.yml
  workers/data_refinery_workers/processors/test_array_express.py
  workers/data_refinery_workers/processors/test_geo.py
  workers/data_refinery_workers/processors/test_no_op.py
  workers/data_refinery_workers/processors/test_salmon.py
  workers/data_refinery_workers/processors/test_transcriptome_index.py
  workers/data_refinery_workers/processors/transcriptome_index.py
  workers/data_refinery_workers/processors/transcriptome_index.yml
  workers/data_refinery_workers/processors/tximport.yml
  workers/data_refinery_workers/processors/utils.py
  workers/dockerfiles/Dockerfile.no_op
Labels: in progress, review

#510 Turn on docker caching layer in circleci.
  .circleci/config.yml
Labels: in progress, review

#507 Dont Trust GEO to Accurately Describe Data As Raw Or Not
  foreman/data_refinery_foreman/surveyor/geo.py
  workers/data_refinery_workers/processors/illumina.py
  workers/data_refinery_workers/processors/test_geo.py
Labels: in progress, review

#503 Allow multiple filters in same category
  api/data_refinery_api/tests.py
  api/data_refinery_api/views.py
Labels: in progress, review

#514 Explicitly Title Samples In Smasher Outputs
  common/data_refinery_common/migrations/0011_computedfile_samples.py
  common/data_refinery_common/models/models.py
  workers/data_refinery_workers/processors/smasher.py
Labels: in progress, review

#517 Make the downloads page faster
  api/data_refinery_api/serializers.py
  api/data_refinery_api/views.py
Labels: in progress, review

#518 Call utils.handle_processor_error properly
  workers/data_refinery_workers/processors/agilent_twocolor.py
  workers/data_refinery_workers/processors/array_express.py
  workers/data_refinery_workers/processors/illumina.py
  workers/data_refinery_workers/processors/no_op.py
  workers/data_refinery_workers/processors/salmon.py
  workers/data_refinery_workers/processors/test_salmon.py
  workers/data_refinery_workers/processors/transcriptome_index.py
Labels: in progress, review

#520 Fix API deploys, prevent logging an error from becoming a new and int…
  infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
  infrastructure/deploy.sh
  workers/data_refinery_workers/downloaders/geo.py
Labels: review

#521 Safer Parallel TXI
  workers/data_refinery_workers/processors/salmon.py
  workers/data_refinery_workers/processors/test_transcriptome_index.py
  workers/data_refinery_workers/processors/transcriptome_index.py
  workers/run_tests.sh
Labels: in progress, review

#522 Improve the way we track nomad queue length to account for running jo…
  infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
Labels: in progress, review

#524 Improve foreman lost job logic so that jobs without their nomad_job_i…
  common/data_refinery_common/message_queue.py
  foreman/data_refinery_foreman/foreman/main.py
  foreman/data_refinery_foreman/foreman/test_main.py
  run_shell.sh
Labels: in progress, review

#505 Make NONE the default transform. Prevent Nomad from overloading dev b…
  common/data_refinery_common/migrations/0012_auto_20180810_1428.py
  common/data_refinery_common/models/models.py
  nomad_client.config
  run_nomad.sh
Labels: in progress, review

#513 Kurtwheeler/unsurveyor
  common/data_refinery_common/models/models.py
  foreman/data_refinery_foreman/surveyor/management/commands/test_unsurvey.py
  foreman/data_refinery_foreman/surveyor/management/commands/unsurvey.py
  foreman/data_refinery_foreman/surveyor/test_end_to_end.py
Labels: in progress, review

#527 Routine issues -> warning; total fail -> error
  workers/data_refinery_workers/downloaders/geo.py
Labels: in progress, review

#534 style: double indent -> single indent
  common/data_refinery_common/utils.py
Labels: in progress, review

#525 Makes downloader and processor jobs complain when they don't have fai…
  common/data_refinery_common/logging.py
  workers/data_refinery_workers/downloaders/utils.py
  workers/data_refinery_workers/processors/utils.py
Labels: in progress, review

#533 R error -> logger
  workers/data_refinery_workers/processors/no_op.py
Labels: in progress, review

#538 Make prepare_image.sh fail if it cannot prepare the image.
  prepare_image.sh
Labels: in progress, review

#536 Check for Permuatations of Non-Normalized Data Filenames
  foreman/data_refinery_foreman/surveyor/geo.py
Labels: in progress, review

#526 Deliver Experiment-Aggregated Metadata in Seperate Files
  workers/data_refinery_workers/processors/smasher.py
  workers/data_refinery_workers/processors/test_smasher.py
Labels: in progress, review

#537 Datasets should always be treated as a single word
  common/data_refinery_common/migrations/0013_auto_20180817_1455.py
  common/data_refinery_common/models/jobs.py
  foreman/data_refinery_foreman/foreman/main.py
Labels: in progress, review

#531 Adds PgBouncer Instance
  infrastructure/environments/dev.tfvars
  infrastructure/environments/prod.tfvars
  infrastructure/environments/staging.tfvars
  infrastructure/instances.tf
  infrastructure/networking.tf
  infrastructure/nomad-configuration/lead-server-instance-user-data.tpl.sh
  infrastructure/nomad-configuration/pg-bouncer-instance-user-data.tpl.sh
  infrastructure/security.tf
Labels: in progress, review

#548 Quick fix of Processor's API
  api/data_refinery_api/serializers.py
  api/data_refinery_api/tests.py
Labels: in progress, review

#519 Adds Quantile Normalization
  .circleci/config.yml
  .circleci/update_docker_img.sh
  common/data_refinery_common/job_lookup.py
  common/data_refinery_common/message_queue.py
  common/data_refinery_common/migrations/0014_auto_20180817_1958.py
  common/data_refinery_common/models/models.py
  workers/data_refinery_workers/processors/management/commands/create_qn_target.py
  workers/data_refinery_workers/processors/qn.yml
  workers/data_refinery_workers/processors/qn_reference.R
  workers/data_refinery_workers/processors/qn_reference.py
  workers/data_refinery_workers/processors/smasher.py
  workers/data_refinery_workers/processors/test_qn_reference.py
  workers/data_refinery_workers/processors/test_smasher.py
  workers/data_refinery_workers/processors/utils.py
  workers/dockerfiles/Dockerfile.smasher
  workers/qn_dependencies.R
  workers/run_command.sh
  workers/run_tests.sh
Labels: in progress, review

#544 Move from 1xEFS to NxEBS High Throughput
  README.md
  api/data_refinery_api/serializers.py
  common/data_refinery_common/message_queue.py
  common/data_refinery_common/migrations/0015_processorjob_volume_index.py
  common/data_refinery_common/models/jobs.py
  common/data_refinery_common/test_utils.py
  common/data_refinery_common/utils.py
  foreman/data_refinery_foreman/surveyor/sra.py
  foreman/data_refinery_foreman/surveyor/test_sra.py
  format_nomad_with_env.sh
  infrastructure/disk.tf
  infrastructure/instances.tf
  infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
  infrastructure/nomad-configuration/client.tpl.hcl
  infrastructure/permissions.tf
  infrastructure/users.tf
  workers/data_refinery_workers/processors/qn_reference.py
  workers/data_refinery_workers/processors/smasher.py
  workers/nomad-job-specs/affymetrix.nomad.tpl
  workers/nomad-job-specs/illumina.nomad.tpl
  workers/nomad-job-specs/no_op.nomad.tpl
  workers/nomad-job-specs/salmon.nomad.tpl
  workers/nomad-job-specs/smasher.nomad.tpl
  workers/nomad-job-specs/transcriptome.nomad.tpl
Labels: in progress, review

#551 Fixes QN Ref Target Test Inputs
  infrastructure/disk.tf
  infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
  workers/data_refinery_workers/processors/qn_reference.py
  workers/data_refinery_workers/processors/smasher.py
  workers/data_refinery_workers/processors/test_qn_reference.py
Labels: in progress, review

#547 Adds processed_samples to Search Response
  api/data_refinery_api/serializers.py
  api/data_refinery_api/tests.py
  common/data_refinery_common/models/models.py
Labels: data for GUI, review

#557 Disables docker layer caching for deploys.
  .circleci/config.yml
Labels: in progress, review

#546 Adds HTML Email Template
  api/data_refinery_api/views.py
  workers/data_refinery_workers/processors/smasher.py
  workers/data_refinery_workers/processors/smasher_email.min.html
Labels: in progress, review

#558 Add Retrier to EBS Mounter
  infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
Labels: in progress, review

#562 Sets the ulimit option for files for nomad clients.
  .circleci/config.yml
  infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
Labels: in progress, review

#566 Increase IPv4 address space of Docker bridge network - I Think
  infrastructure/nomad-configuration/client-instance-user-data.tpl.sh
Labels: in progress, review

#563 Adds `has_email` property to Dataset API response
  api/data_refinery_api/serializers.py
  common/data_refinery_common/models/models.py
Labels: in progress, review

#567 Lowers ascp Warning Level and Reduce Retry Wait Period
  workers/data_refinery_workers/downloaders/geo.py
  workers/data_refinery_workers/downloaders/sra.py
Labels: in progress, review

#564 Update README to only include `survey_all`
  README.md
Labels: in progress, review

#560 Update .dockerignore nomad-job-specs
  .dockerignore
Labels: in progress, review

#573 Add assembly_name to OrganismIndex API
  api/data_refinery_api/serializers.py
Labels: in progress, review

#575 Allow deploys to continue if image tages already exist.
  .circleci/update_docker_img.sh
Labels: in progress, review

#578 Minor updates to readme due to survey dispatching changes.
  README.md
Labels: in progress, review

#579 Fixes up a few mistakes in the last deploy PR.
  .circleci/update_docker_img.sh
Labels: in progress, review

#580 Make sure certbot has HTTP access to the server it's running on
  infrastructure/api-configuration/api-server-instance-user-data.tpl.sh
Labels: in progress, review
